### ISSUE TITLE
Missing docker registry part

### ISSUE THREAD

**Issue by dmitry-yackevich** [vfarcic/vfarcic.github.io#1]
vagrant@cd:~/books-ms$ sudo docker push 10.100.198.200:5000/books-ms
The push refers to a repository [10.100.198.200:5000/books-ms] (len: 1)
Sending image list
Put http://10.100.198.200:5000/v1/repositories/books-ms/: dial tcp 10.100.198.200:5000: connection refused

fixed by 
docker run -p 5000:5000 -d registry

**Comment by vfarcic** [comment]
When you create the VM with `vagrant up cd`, provisioner is executed that, among other things, makes sure that the registry container is running. However, vagrant runs the provisioners only when creating the VM. To execute provisioners always (for example after you stopped the VM with `vagrant halt cd`), add the `--provision` flag. It should be something like `vagrant up cd --provision`. I think I used that flag throughout the prosentation. If that's not the case, can you please let me know which part caused problems?
